### PR TITLE
Fix usage of Expression constraint

### PR DESCRIPTION
**Pull request by enumag**
I'm trying to fix it in symfony but it probably won't be fixed any time soon because it's a BC break.

https://github.com/symfony/symfony/pull/16166

### CODE REVIEW

**Comment by fprochazka** [comment]
I believe you know what you're doing, but we should probably start writing more tests for this lib :)

**Comment by enumag** [comment]
I agree but I'm a bit unwilling to write theme because I'm not so familiar with Nette Tester.

**Comment by enumag** [comment]
@fprochazka By the way can we tag 0.3.1? The other changes I've planned might not be entirely compatible.

**Comment by fprochazka** [comment]
More like 0.4 already

**Comment by enumag** [comment]
Really? The DoctrineCache feature should be fully compatible.

**Comment by fprochazka** [comment]
Yeah, but I wanna have a gap ready if I need to start tagging versions for nette 2.3 and 2.2 separately.

**Comment by enumag** [comment]
I still think 0.3.1 would be fine now but do as you wish. ;-)

**Pull request merged**
