### PR TITLE
Revert ConstraintValidatorFactory refactoring

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by enumag** [comment]
@fprochazka Tests are passing now, Travis failed because of old array syntax. Should this branch support PHP 5.3 or not?

**Comment by fprochazka** [comment]
I guess it would be better to also revert the array converts to make this the last PHP 5.3 compatible release. What do you think? I suppose it would at least make the revert easier.

**Comment by enumag** [comment]
Doesn't really matter since I've already fixed the conflicts.

**Comment by enumag** [comment]
@fprochazka Short arrays reverted, tests are passing now. Review please. ;-)

**Comment by fprochazka** [comment]
I have no easy way to verify it works right now. Since you use it extensively, did you test in on some of your projects I suppose?

**Comment by enumag** [comment]
I did not. My application requires the 0.4 version, not this one. But since the tests are passing now it should be fine imo.

**Comment by fprochazka** [comment]
cc @Majkl578 do you happen to have some application that would require such `0.3.2` release, please?

**Comment by Majkl578** [comment]
Unfortunatey not, I'm not using it anywhere now...

**Comment by fprochazka** [comment]
I'll try to put some sort of verification for this at the evening. Thanks anyway, and thanks for your work @enumag !

**Comment by enumag** [comment]
@fprochazka I think it is too late to revert this. Right?

**Pull request closed without merging**
