### PR TITLE
Updated branch alias

### PR DESCRIPTION
**Pull request by enumag**
There are incompatible changes in master so the next version won't be 0.2.1 but 0.3 in my opinion (or 1.0).

### CODE REVIEW

**Comment by fprochazka** [comment]
You're right :)

**Comment by fprochazka** [comment]
I was restarting the tests so we'd have a nice green before I merge it but the composer kept failing :-/

**Comment by enumag** [comment]
I see. :-) I was wandering why you didn't merge it right away. Well it seems we have a green now though so I guess your restarts were eventually successful.

**Comment by fprochazka** [comment]
Yes. But it's not like there is some test for the branch alias, so it doesn't matter :)

**Pull request merged**
