### PR TITLE
Make Kdyby/Annotations optional

### PR DESCRIPTION
**Pull request by enumag**
Same as Doctrine, Validator can get the configuration by other means than annotations so the dependency should be optional.

Not that I need it personally but still a good idea imo.

### CODE REVIEW

**Comment by enumag** [comment]
Added tests (refactored the old tests as well).

**Comment by enumag** [comment]
Updated installation instructions (kdyby/annotations has to be installed manually now).

**Comment by enumag** [comment]
@fprochazka What do you think about this?

**Comment by enumag** [comment]
ping @fprochazka

**Comment by fprochazka** [comment]
Awesome!

**Pull request merged**
